Most of the error checking in postinst before creating the debian-mixminion user is actually rather counterproductive, as adduser already does all of the job, only much better.  Therefore comment it out.

diff --git a/debian/mixminion.postinst b/debian/mixminion.postinst
--- a/debian/mixminion.postinst
+++ b/debian/mixminion.postinst
@@ -1,32 +1,32 @@
 #!/bin/sh -e
 
 # checking debian-mixminion account
-
-uid=`getent passwd debian-mixminion | cut -d ":" -f 3`
-home=`getent passwd debian-mixminion | cut -d ":" -f 6`
-
-# if there is the uid the account is there and we can do
-# the sanit(ar)y checks otherwise we can safely create it.
-
-if [ "$uid" ]; then
-    # guess??? the checks!!!
-    if [ $uid -ge 100 ] && [ $uid -le 999 ]; then
-    	echo "debian-mixminion uid check: ok"
-    else
-    	echo "ERROR: debian-mixminion account has a non-system uid!"
-	echo "Please check /usr/share/doc/mixminion/README.Debian on how to"
-	echo "correct this problem"
-	exit 1
-    fi
-    if [ "$home" = "/var/lib/mixminion" ]; then
-        echo "debian-mixminion homedir check: ok"
-    else
-	echo "ERROR: debian-mixminion account has an invalid home directory!"
-	echo "Please check /usr/share/doc/mixminion/README.Debian on how to"
-	echo "correct this problem"
-	exit 1
-    fi
-else
+## 
+## uid=`getent passwd debian-mixminion | cut -d ":" -f 3`
+## home=`getent passwd debian-mixminion | cut -d ":" -f 6`
+## 
+## # if there is the uid the account is there and we can do
+## # the sanit(ar)y checks otherwise we can safely create it.
+## 
+## if [ "$uid" ]; then
+##     # guess??? the checks!!!
+##     if [ $uid -ge 100 ] && [ $uid -le 999 ]; then
+##     	echo "debian-mixminion uid check: ok"
+##     else
+##     	echo "ERROR: debian-mixminion account has a non-system uid!"
+## 	echo "Please check /usr/share/doc/mixminion/README.Debian on how to"
+## 	echo "correct this problem"
+## 	exit 1
+##     fi
+##     if [ "$home" = "/var/lib/mixminion" ]; then
+##         echo "debian-mixminion homedir check: ok"
+##     else
+## 	echo "ERROR: debian-mixminion account has an invalid home directory!"
+## 	echo "Please check /usr/share/doc/mixminion/README.Debian on how to"
+## 	echo "correct this problem"
+## 	exit 1
+##     fi
+## else
     # what this might mean?? oh creating a system l^Huser!
     adduser --quiet \
             --system \
@@ -36,7 +36,7 @@ else
 	    --shell /bin/bash \
 	    --group \
     debian-mixminion
-fi
+## fi
 
 # ch{owning,moding} things around
 # We will do nothing across upgrades.
